# Generated by Django 5.1.4 on 2024-12-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=100)),
                ('uphone', models.BigIntegerField()),
                ('upassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('etitle', models.CharField(max_length=100)),
                ('edesc', models.CharField(max_length=100)),
                ('ecity', models.CharField(max_length=100)),
                ('elocation', models.CharField(max_length=100)),
                ('edate', models.DateField()),
                ('etime', models.TimeField()),
                ('vticket', models.IntegerField()),
                ('gticket', models.IntegerField()),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bdate', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('eid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
