# Generated by Django 5.1.4 on 2024-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ttype',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
